"""Inicializacion

Revision ID: 16ff0ae3e3b2
Revises: 
Create Date: 2025-12-02 14:55:25.292947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ff0ae3e3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sitio', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=False),
    sa.Column('ha_habilitado', sa.Boolean(), nullable=True),
    sa.Column('segundo_serial', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('policies',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('vdom', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('src_intf', sa.Text(), nullable=True),
    sa.Column('dst_intf', sa.Text(), nullable=True),
    sa.Column('src_addr', sa.Text(), nullable=True),
    sa.Column('dst_addr', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('bytes_raw', sa.String(length=50), nullable=True),
    sa.Column('bytes_int', sa.BigInteger(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nat', sa.String(length=20), nullable=True),
    sa.Column('users', sa.Text(), nullable=True),
    sa.Column('groups', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_policy_id'), ['policy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_policy_id'))

    op.drop_table('policies')
    op.drop_table('users')
    op.drop_table('equipos')
    # ### end Alembic commands ###
